
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Read rather than demanded. Prisma's `env()` helper throws when the
    // variable is missing, which stopped `prisma generate` — the one command
    // that never opens a database — from running without one. Generating the
    // client happens on install, before anybody has written a `.env`, so that
    // refusal was the first thing a fresh checkout hit. The commands that do
    // need a database still fail on an empty URL, and say so.
    url: process.env.DATABASE_URL ?? "",
  },
});
