#!/usr/bin/env node
/**
 * Says what is wrong with the Prisma install before the dev server does.
 *
 * The generated client and the runtime it imports are one thing shipped as two
 * packages. When they don't match — a client generated by Prisma 6 against a
 * runtime that has moved on to 7, which no longer exports `runtime/library` —
 * the only thing anybody sees is Turbopack failing to resolve a module inside
 * generated code, on a line nobody wrote and nobody can fix. That error names
 * the symptom and hides the cause.
 *
 * So the cause is checked here, where it can be said in words, and the fix
 * printed with it. Runs before `dev` and `build`.
 */
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const require = createRequire(path.join(root, "package.json"));

/** What the project asks for, and what is actually installed beside it. */
function versions(name) {
  const { dependencies = {}, devDependencies = {} } = JSON.parse(
    readFileSync(path.join(root, "package.json"), "utf8")
  );
  const wanted = dependencies[name] ?? devDependencies[name] ?? null;
  let installed = null;
  let from = null;
  try {
    const manifest = require.resolve(`${name}/package.json`);
    installed = JSON.parse(readFileSync(manifest, "utf8")).version;
    from = manifest;
  } catch {
    // Not installed at all, which the report below says in as many words.
  }
  return { wanted, installed, from };
}

function fail(lines) {
  console.error(`\n  Prisma is not installed the way this project needs.\n`);
  for (const line of lines) console.error(`  ${line}`);
  console.error(`\n  Fix it with:\n`);
  console.error(`    rm -rf node_modules .next src/generated`);
  console.error(`    npm ci\n`);
  console.error(
    `  If npm ci complains that the lockfile is out of sync, your checkout has`
  );
  console.error(
    `  drifted from the repository — git status, then git reset --hard origin/main`
  );
  console.error(`  once you have kept anything you still want.\n`);
  process.exit(1);
}

const client = versions("@prisma/client");
const cli = versions("prisma");

if (!client.installed) {
  fail([
    `@prisma/client is not installed. The project asks for ${client.wanted}.`,
  ]);
}

// The two halves have to be the same build. This is the mismatch that produces
// "Can't resolve '@prisma/client/runtime/library'".
if (cli.installed && cli.installed !== client.installed) {
  fail([
    `prisma (the generator) is ${cli.installed}`,
    `@prisma/client (the runtime) is ${client.installed}`,
    `They must be the same version. The project asks for ${client.wanted}.`,
  ]);
}

if (client.wanted && !client.wanted.startsWith("^") && client.wanted !== client.installed) {
  fail([
    `@prisma/client ${client.installed} is installed, but this project pins ${client.wanted}.`,
    `Resolved from ${client.from}`,
  ]);
}

// The import the generated client actually makes. Checking it directly catches
// anything the version numbers alone would miss.
try {
  require.resolve("@prisma/client/runtime/library");
} catch {
  fail([
    `@prisma/client ${client.installed} does not provide "runtime/library",`,
    `which is the module the generated client imports.`,
    `Resolved from ${client.from}`,
  ]);
}
