#!/usr/bin/env node
/**
 * The two things that stop this project starting for reasons that have nothing
 * to do with the code, said plainly before the dev server gets a chance to say
 * them badly. Runs before `dev` and `build`.
 *
 * Says what is wrong with the Prisma install before the dev server does.
 *
 * The generated client and the runtime it imports are one thing shipped as two
 * packages. When they don't match — a client generated by Prisma 6 against a
 * runtime that has moved on to 7, which no longer exports `runtime/library` —
 * the only thing anybody sees is Turbopack failing to resolve a module inside
 * generated code, on a line nobody wrote and nobody can fix. That error names
 * the symptom and hides the cause.
 *
 * So the cause is checked here, where it can be said in words, and the fix
 * printed with it.
 */
import { createRequire } from "node:module";
import { readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const require = createRequire(path.join(projectRoot, "package.json"));

/** What the project asks for, and what is actually installed beside it. */
function versions(name) {
  const { dependencies = {}, devDependencies = {} } = JSON.parse(
    readFileSync(path.join(projectRoot, "package.json"), "utf8")
  );
  const wanted = dependencies[name] ?? devDependencies[name] ?? null;
  let installed = null;
  let from = null;
  try {
    const manifest = require.resolve(`${name}/package.json`);
    installed = JSON.parse(readFileSync(manifest, "utf8")).version;
    from = manifest;
  } catch {
    // Not installed at all, which the report below says in as many words.
  }
  return { wanted, installed, from };
}

function fail(lines) {
  console.error(`\n  Prisma is not installed the way this project needs.\n`);
  for (const line of lines) console.error(`  ${line}`);
  console.error(`\n  Fix it with:\n`);
  console.error(`    rm -rf node_modules .next src/generated`);
  console.error(`    npm ci\n`);
  console.error(
    `  If npm ci complains that the lockfile is out of sync, your checkout has`
  );
  console.error(
    `  drifted from the repository — git status, then git reset --hard origin/main`
  );
  console.error(`  once you have kept anything you still want.\n`);
  process.exit(1);
}

const client = versions("@prisma/client");
const cli = versions("prisma");

if (!client.installed) {
  fail([
    `@prisma/client is not installed. The project asks for ${client.wanted}.`,
  ]);
}

// The two halves have to be the same build. This is the mismatch that produces
// "Can't resolve '@prisma/client/runtime/library'".
if (cli.installed && cli.installed !== client.installed) {
  fail([
    `prisma (the generator) is ${cli.installed}`,
    `@prisma/client (the runtime) is ${client.installed}`,
    `They must be the same version. The project asks for ${client.wanted}.`,
  ]);
}

if (client.wanted && !client.wanted.startsWith("^") && client.wanted !== client.installed) {
  fail([
    `@prisma/client ${client.installed} is installed, but this project pins ${client.wanted}.`,
    `Resolved from ${client.from}`,
  ]);
}

// The import the generated client actually makes. Checking it directly catches
// anything the version numbers alone would miss.
try {
  require.resolve("@prisma/client/runtime/library");
} catch {
  fail([
    `@prisma/client ${client.installed} does not provide "runtime/library",`,
    `which is the module the generated client imports.`,
    `Resolved from ${client.from}`,
  ]);
}


/**
 * Turbopack keeps its cache in a directory it reads by parsing file names as
 * numbers. One file it can't parse and the whole cache refuses to open:
 *
 *   Failed to open database
 *     0: Loading persistence directory failed
 *     1: invalid digit found in string
 *
 * which names neither the file nor the folder, and leaves a dev server that
 * says "Ready" and then serves nothing at all.
 *
 * On a Mac that file is nearly always `.DS_Store`, written by Finder into any
 * folder somebody opens — and written again and again when the project lives
 * in an iCloud-synced Documents, which also leaves `.icloud` placeholders and
 * `._` forks of its own.
 *
 * Only that junk is swept, by name. Everything else in there belongs to the
 * cache — it keeps a `CURRENT`, a `LOG` and a `MANIFEST` beside its numbered
 * files, and deleting those would break a cache that was working. Anything
 * unrecognised is reported rather than removed: a stray file is cheap to
 * mention and expensive to guess wrong about.
 */
const OS_JUNK = [
  /^\.DS_Store$/,
  /^\._/,
  /^\.Spotlight-V100$/,
  /^\.Trashes$/,
  /^\.fseventsd$/,
  /^Thumbs\.db$/i,
  /^desktop\.ini$/i,
  /\.icloud$/,
];

/** What the cache itself is allowed to have in there, beside numbered files. */
const CACHE_OWN = [/^\d+/, /^CURRENT$/, /^LOCK$/, /^LOG(\.old)?$/, /^MANIFEST/, /^OPTIONS/];

function sweepBundlerCache() {
  const swept = [];
  const puzzling = [];

  for (const root of [
    ".next/dev/cache/turbopack",
    ".next/build/cache/turbopack",
    ".next/cache/turbopack",
  ]) {
    const at = path.join(projectRoot, root);
    let versions;
    try {
      versions = readdirSync(at);
    } catch {
      continue; // No cache yet, which is the healthy empty case.
    }
    for (const version of versions) {
      const dir = path.join(at, version);
      let entries;
      try {
        if (!statSync(dir).isDirectory()) continue;
        entries = readdirSync(dir);
      } catch {
        continue;
      }
      for (const entry of entries) {
        // Junk is decided first: an iCloud placeholder is named after the file
        // it stands in for, so it would otherwise pass as one of the cache's
        // own numbered files.
        if (!OS_JUNK.some((junk) => junk.test(entry))) {
          if (!CACHE_OWN.some((ok) => ok.test(entry))) {
            puzzling.push(`${root}/${version}/${entry}`);
          }
          continue;
        }
        try {
          rmSync(path.join(dir, entry), { recursive: true, force: true });
          swept.push(entry);
        } catch {
          puzzling.push(`${root}/${version}/${entry}`);
        }
      }
    }
  }

  if (swept.length > 0) {
    console.log(
      `  Swept ${swept.join(", ")} out of the bundler cache — Turbopack can't read a folder with those in it.`
    );
  }
  if (puzzling.length > 0) {
    console.error(
      `\n  Something that isn't Turbopack's is sitting in its cache:\n` +
        puzzling.map((f) => `    ${f}`).join("\n") +
        `\n\n  If the dev server says "Failed to open database", delete .next and start again.\n`
    );
  }
}

sweepBundlerCache();
